// Generated by scripts/import-emis.ts — one loader per imported province.
// Loaded lazily so the directory JSON is only read when Supabase isn't configured.
export const DIRECTORY_LOADERS: Array<() => Promise<{ default: unknown }>> = [
  () => import("./western-cape.json"),
];
